apiVersion: v1
kind: Service
metadata:
  name: {{ include "tyk-sre-tool.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tyk-sre-tool.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
